language: ruby
env:
  global:
    - GIT_COMMITTER_NAME: "k2nr"
    - GIT_COMMITTER_EMAIL: "likerichie+github@gmail.com"
    - GIT_AUTHOR_NAME: "k2nr"
    - GIT_AUTHOR_EMAIL: "likerichie+github@gmail.com"
    - secure: "W7NTB52lCUChGTV0nbUVpuEubGeawz+Sh8ugMzIAnEkYZP15phbRzMHGj7pFF5yn+4iRDYbbnUH4CkdHqoQE4mhPNiyedCq4oEe0VU4dlaMWiOGGgrsBkW/UJcVbZgNKbWaBPQk/jJegRmJPQ9WKTSbgV4YM29CENMe8MoIhX4Y="
script:
    - bundle exec middleman build
after_success:
    - cd build
    - git init
    - git add --all
    - git commit -m "updated by Travis CI"
    - 'git push --quiet https://$GH_TOKEN@github.com/k2nr/k2nr.github.com.git master -f 2> /dev/null'
branches:
  only:
    - source
